In [ ]:
import numpy as np
from kingdon.blademap  import BladeMap
from kingdon import Algebra
from kingdon.numerical import exp 

sta  = Algebra(1,3,0,start_index=0) # spacetime algebra
#vga3 = Algebra(3,0,0,start_index=1) # space algebra
pga3 = Algebra(3,0,1,start_index=0) # projective geometric algebra
D = sta.blades  # Dirac basis
P = pga3.blades # Pauli basis

bm = BladeMap([(D.e01,P.e1),
               (D.e02,P.e2),
               (D.e03,P.e3),
               (D.e12,P.e12),
               (D.e23,P.e23),
               (D.e13,P.e13),
               (D.e0123,P.e123)])

def split(X): # space time split 
    return bm(X.odd*D.e0+X.even)

bound = 2
pts   = 2
grid_1d = np.linspace(-bound,bound,pts)
X0, X1, X2, X3 = np.meshgrid(*[grid_1d]*4,indexing='ij')
#X0[...] = 1
x = (X0*D.e0+ X1*D.e1 + X2*D.e2 + X3*D.e3 )#.dual()
#x = X1*e1 + X2*e2 + X3*e3# + X4*e4

def F(x, P=D.e123+.1*D.e012, F0=D.e01 + D.e13):
    xP = x^P
    return exp(xP)*F0*exp(~xP)

In [25]:

EiB = split(F(x))
E, B = EiB.odd, EiB.even.dual()
E, B # electric and magnetic fields
E

[[[[-0.89683276 -0.30839262]
   [-0.89683276 -0.30839262]]

  [[-0.89683276 -0.30839262]
   [-0.89683276 -0.30839262]]]


 [[[-0.30839262 -0.89683276]
   [-0.30839262 -0.89683276]]

  [[-0.30839262 -0.89683276]
   [-0.30839262 -0.89683276]]]] 𝐞₁ + [[[[ 0.44234059  0.9506277 ]
   [ 0.44234059  0.9506277 ]]

  [[ 0.44234059  0.9506277 ]
   [ 0.44234059  0.9506277 ]]]


 [[[-0.9506277  -0.44234059]
   [-0.9506277  -0.44234059]]

  [[-0.9506277  -0.44234059]
   [-0.9506277  -0.44234059]]]] 𝐞₂